language: java
jdk:
 - openjdk8
addons:
  sonarcloud:
    organization: "unimibsoftengcourse2021"
    token:
      secure: $SONAR_TOKEN
script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=myorg_myrepo
